<a href="https://colab.research.google.com/github/monicasofiarestrepo/InvestigacionDeOperaciones/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cvxpy as cvx
import numpy as np

In [ ]:
#@title Asignación

# Variables de decisión
x = cvx.Variable((3,3), boolean = True)

# Función objetivo
c = [
    [10,9,6],
    [15,18,14],
    [9,5,3]
    ]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # De oferta:
     cvx.sum(x[0,:]) <= 1,
     cvx.sum(x[1,:]) <= 1,
     cvx.sum(x[2,:]) <= 1,

    # De demanda:
     cvx.sum(x[:,0]) >= 1,
     cvx.sum(x[:,1]) >= 1,
     cvx.sum(x[:,2]) >= 1,
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

# Impresiones
print(P.status)
print(P.value)
print(x.value)


optimal
26.0
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
#@title Asignación

# Variables de decisión
x = cvx.Variable((4,3), boolean = True)

# Función objetivo
c = [
    [10,9,6,0],
    [15,18,14,0],
    [9,5,3,0]
    ]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # De oferta:
     cvx.sum(x[0,:]) <= 1,
     cvx.sum(x[1,:]) <= 1,
     cvx.sum(x[2,:]) <= 1,
     cvx.sum(x[3,:]) <= 1,

    # De demanda:
     cvx.sum(x[:,0]) >= 1,
     cvx.sum(x[:,1]) >= 1,
     cvx.sum(x[:,2]) >= 2,
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

# Impresiones
print(P.status)
print(P.value)
print(x.value)

optimal
18.0
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]
