<a href="https://colab.research.google.com/github/monicasofiarestrepo/InvestigacionDeOperaciones/blob/main/Asignacion_IO_luis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import cvxpy as cvx
import numpy as np

In [ ]:
#@title Asignación

# Variables de decisión
x = cvx.Variable((3,3), boolean = True)

# Función objetivo
c = [
    [10,9,6],
    [15,18,14],
    [9,5,3]
    ]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # De oferta:
     cvx.sum(x[0,:]) <= 1,
     cvx.sum(x[1,:]) <= 1,
     cvx.sum(x[2,:]) <= 1,

    # De demanda:
     cvx.sum(x[:,0]) >= 1,
     cvx.sum(x[:,1]) >= 1,
     cvx.sum(x[:,2]) >= 1,
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

# Impresiones
print(P.status)
print(P.value)
print(x.value)


In [ ]:
#@title Asignación con Holgura

# Variables de decisión
x = cvx.Variable((4,3), boolean = True)

# Función objetivo
c = [
    [10,9,6,0],
    [15,18,14,0],
    [9,5,3,0]
    ]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # De oferta:
     cvx.sum(x[0,:]) <= 1,
     cvx.sum(x[1,:]) <= 1,
     cvx.sum(x[2,:]) <= 1,
     cvx.sum(x[3,:]) <= 1,

    # De demanda:
     cvx.sum(x[:,0]) >= 1,
     cvx.sum(x[:,1]) >= 1,
     cvx.sum(x[:,2]) >= 2,
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

# Impresiones
print(P.status)
print(P.value)
print(x.value)

In [ ]:
#@title Red de computadores (TRASBORDO)
# Variables de decisión
x = cvx.Variable((7,7), boolean = True)

# Función objetivo
c = [
    [99999,99999,3    ,4    ,99999,99999,99999],
    [99999,99999,2    ,5    ,99999,99999,99999],
    [99999,99999,99999,7    ,8    ,6    ,99999],
    [99999,99999,99999,99999,99999,4    ,9    ],
    [99999,99999,99999,99999,99999,5    ,99999],
    [99999,99999,99999,99999,99999,99999,3    ],
    [99999,99999,99999,99999,99999,99999,99999],
    ]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # De oferta:
     cvx.sum(x[0,:]) <= 1,
     cvx.sum(x[1,:]) <= 1,
     cvx.sum(x[2,:]) <= 1,

    # De demanda:
     cvx.sum(x[:,0]) >= 1,
     cvx.sum(x[:,1]) >= 1,
     cvx.sum(x[:,2]) >= 1,
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

# Impresiones
print(P.status)
print(P.value)
print(x.value)


optimal
12.0
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [3]:
#@title Constructora
# Variables de decisión
x = cvx.Variable((5,4), boolean = True)

# Función objetivo
c = [
      [10,8,8,5,8],
      [9,7,6,7,7],
      [6,6,5,7,6],
      [5,6,6,6,5]
    ]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # De oferta:

     cvx.sum(x[0,:]) <= 1,
     cvx.sum(x[1,:]) <= 1,
     cvx.sum(x[2,:]) <= 1,
     cvx.sum(x[3,:]) <= 1,
     cvx.sum(x[4,:]) <= 1,

    # De demanda:
     cvx.sum(x[:,0]) >= 1,
     cvx.sum(x[:,1]) >= 1,
     cvx.sum(x[:,2]) >= 1,
     cvx.sum(x[:,3]) >= 1,
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

# Impresiones
print(P.status)
print(P.value)
print(x.value)


optimal
22.0
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#@title Traductor
# Variables de decisión
x = cvx.Variable((5,4), boolean = True)

# Función objetivo
c = [
      [60 ,116,120,114,0],
      [105,109,102,105,0],
      [105,107,113,118,0],
      [110,96 ,111,115,0]
    ]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # De oferta:

     cvx.sum(x[0,:]) <= 1,
     cvx.sum(x[1,:]) <= 1,
     cvx.sum(x[2,:]) <= 1,
     cvx.sum(x[3,:]) <= 1,
     cvx.sum(x[4,:]) <= 1,


    # De demanda:
     cvx.sum(x[:,0]) >= 2,
     cvx.sum(x[:,1]) >= 1,
     cvx.sum(x[:,2]) >= 1,
     cvx.sum(x[:,3]) >= 1,

     #extras:
     #x[0,0] == 0,
     #x[3,3] == 0
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

# Impresiones
print(P.status)
print(P.value)
print(x.value)


optimal
372.0
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
#@title Empresa
# Variables de decisión
x = cvx.Variable((4,3), boolean = True)

# Función objetivo
c = [
      [8 , 17, 19, 17],
      [12, 11, 6 , 8 ],
      [16, 16, 6 , 19],
 
    ]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # De oferta:

     cvx.sum(x[0,:]) <= 1,
     cvx.sum(x[1,:]) <= 1,
     cvx.sum(x[2,:]) <= 1,


    # De demanda:
     cvx.sum(x[:,0]) >= 1,
     cvx.sum(x[:,1]) >= 1,
     cvx.sum(x[:,2]) >= 1,

]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

# Impresiones
print(P.status)
print(P.value)
print(x.value)


optimal
22.0
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [ ]:
#@title Gobierno fotovoltaica
# Variables de decisión
x = cvx.Variable((3,3), boolean = True)

# Función objetivo
c = [
      [175, 292, 319],
      [190, 370, 170],
      [254, 148, 350]
    ]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # De oferta:

     cvx.sum(x[0,:]) <= 1,
     cvx.sum(x[1,:]) <= 1,
     cvx.sum(x[2,:]) <= 1,

    # De demanda:
     cvx.sum(x[:,0]) >= 1,
     cvx.sum(x[:,1]) >= 1,
     cvx.sum(x[:,2]) >= 1

]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

# Impresiones
print(P.status)
print(P.value)
print(x.value)


optimal
493.0
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [ ]:
#@title Fabrica mantenimiento
# Variables de decisión
x = cvx.Variable((3,3), boolean = True)

# Función objetivo
c = [
      [15,9,5],
      [9,8,2],
      [5,3,7]
    ]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # De oferta:

     cvx.sum(x[0,:]) <= 1,
     cvx.sum(x[1,:]) <= 1,
     cvx.sum(x[2,:]) <= 1,

    # De demanda:
     cvx.sum(x[:,0]) >= 1,
     cvx.sum(x[:,1]) >= 1,
     cvx.sum(x[:,2]) >= 1,
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

# Impresiones
print(P.status)
print(P.value)
print(x.value)


optimal
16.0
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
#@title Reality show
# Variables de decisión
x = cvx.Variable((4,4), boolean = True)

# Función objetivo
c = [
      [27,28.5,26,29],
      [27.5,28.5,26.5,30],
      [25.9,26,27,27.5],
      [26.5,26,28,28.5]
    ]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # De oferta:

     cvx.sum(x[0,:]) <= 1,
     cvx.sum(x[1,:]) <= 1,
     cvx.sum(x[2,:]) <= 1,
     cvx.sum(x[3,:]) <= 1,

    # De demanda:
     cvx.sum(x[:,0]) >= 1,
     cvx.sum(x[:,1]) >= 1,
     cvx.sum(x[:,2]) >= 1,
     cvx.sum(x[:,3]) >= 1,

     #extra
     x[0,3] == 1
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

# Impresiones
print(P.status)
print(P.value)
print(x.value)


optimal
108.0
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
