<h1>Problema plantas de produccion</h1>
<img src="transporteSevillaSantander.png">

In [2]:
import cvxpy as cvx
import numpy as np

In [7]:
# Variables de decisión
x = cvx.Variable((2,3), nonneg = True)

# Función objetivo:

c = [
    [5*538 ,5*393],
    [5*1046,5*693],
    [5*439 ,5*673],
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # oferta
    cvx.sum(x[0,:]) <= 350,
    cvx.sum(x[1,:]) <= 600,

     
     # demanda
    cvx.sum(x[:,0]) >= 325,
    cvx.sum(x[:,1]) >= 300,
    cvx.sum(x[:,2]) >= 275,
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

var9
minimize Sum([[2690. 5230. 2195.]
 [1965. 3465. 3365.]] @ var9, None, False)
optimal
2299875.0001551765
[[ 25.   0. 275.]
 [300. 300.   0.]]


<h1>Problema Minas</h1>
<img src="MInas-Centro.png">

In [97]:
#Variable de decision
x=cvx.Variable((3,4),nonneg = True)

#Funcion objetivo

c = [
    [484,449,890],
    [564,658,542],
    [778,324,538],
    [793,704,596]
]

Z =  cvx.Minimize(cvx.sum(cvx.multiply(c,x)))
#Restricciones

r=[
    #Oferta
    cvx.sum(x[0,:])<=75,
    cvx.sum(x[1,:])<=125,
    cvx.sum(x[2,:])<=100,

    #Demanda

    cvx.sum(x[:,0])>=80,
    cvx.sum(x[:,1])>=65,
    cvx.sum(x[:,2])>=70,
    cvx.sum(x[:,3])>=85
]

P = cvx.Problem(Z,r)
P.solve()
print(P.status)
print(round(P.value,2))
print(np.round(x.value,0))

optimal
146465.0
[[25. 50.  0.  0.]
 [55.  0. 70.  0.]
 [ 0. 15.  0. 85.]]


<h1>Turbinas Eolicas</h1>
<img src="Turbinas-Eolicas.png">

In [118]:
#Variables de decision, o sea Generados producidos por mes
x=cvx.Variable((4,1),nonneg=True)
costos=[[190,239,179,253]]

#Funcion objetivo
DemandaAgosto=10
DemandaSeptiembre=15
DemandaOctubre=25
DemandaNoviembre=20
Z=cvx.Minimize(cvx.sum(cvx.multiply(costos,x)) +2*(DemandaAgosto + x[0] -DemandaAgosto + x[0] -DemandaSeptiembre + x[1] + x[2] -DemandaAgosto + x[0] -DemandaSeptiembre + x[1] -DemandaOctubre))

#Restricciones

r = [
    #Oferta 
    x[0]<=21,
    x[1]<=33,
    x[2]<=28,
    x[3]<=21,
    #Demanda
    x[0] >= DemandaAgosto,
    x[1] -DemandaAgosto + x[0] >= DemandaSeptiembre,
    x[2] -DemandaAgosto + x[0] -DemandaSeptiembre + x[1]>= DemandaOctubre,
    x[3] + x[2] -DemandaAgosto + x[0] -DemandaSeptiembre + x[1] -DemandaOctubre >= 20,

]

#Configurar

P=cvx.Problem(Z,r)

#SOl
P.solve()
print(x[0].value)
print(P.status)
print(round(P.value,5))
print(np.round(x.value,0))


[21.00000001]
optimal
13885.00001
[[21.]
 [21.]
 [28.]
 [ 0.]]


<h1>Problema Distribucion de agua</h1>
<img src="Agua.png">

In [107]:
# Caso oferta=Demanda

#Variable de decision
x=cvx.Variable((3,4),nonneg = True)

#Funcion objetivo

c = [
    [5,3,6],
    [2,6,1],
    [5,6,2],
    [3,5,4]
]

Z =  cvx.Minimize(cvx.sum(cvx.multiply(c,x)))
#Restricciones

print(cvx.multiply(c,x))

r=[
    #Oferta
    cvx.sum(x[0,:])<=50,
    cvx.sum(x[1,:])<=60,
    cvx.sum(x[2,:])<=50,

    #Demanda

    cvx.sum(x[:,0])>=30,
    cvx.sum(x[:,1])>=70,
    cvx.sum(x[:,2])>=0,
    cvx.sum(x[:,3])>=10,
    

]

P = cvx.Problem(Z,r)
P.solve()
print(P.status)
print(round(P.value,2))
print(np.round(x.value,0))

[[5. 2. 5. 3.]
 [3. 6. 6. 5.]
 [6. 1. 2. 4.]] @ var15553
optimal
210.0
[[ 0. 20.  0. 10.]
 [30.  0.  0.  0.]
 [ 0. 50.  0.  0.]]


In [114]:
# Caso oferta>Demanda y se tienen gastar todos los recursos

#Variable de decision
x=cvx.Variable((3,4),nonneg = True)

#Funcion objetivo

c = [
    [5,3,6],
    [5,8,1],
    [7,6,2],
    [1,6,4]
]

Z =  cvx.Minimize(cvx.sum(cvx.multiply(c,x)))
#Restricciones

print(cvx.multiply(c,x))

r=[
    #Oferta
    cvx.sum(x[0,:])==50,
    cvx.sum(x[1,:])==60,
    cvx.sum(x[2,:])==50,

    #Demanda

    cvx.sum(x[:,0])>=30,
    cvx.sum(x[:,1])>=70,
    cvx.sum(x[:,2])>=0,
    cvx.sum(x[:,3])>=10,
    
    
]

P = cvx.Problem(Z,r)
P.solve()
print(P.status)
print(round(P.value,2))
print(np.round(x.value,0))

[[5. 5. 7. 1.]
 [3. 8. 6. 6.]
 [6. 1. 2. 4.]] @ var16462
optimal
360.0
[[ 0. 20.  0. 30.]
 [60.  0.  0.  0.]
 [ 0. 50.  0.  0.]]


In [106]:
## Caso demanda > oferta


#Variable de decision
x=cvx.Variable((4,4),nonneg = True)

#Funcion objetivo

c = [
    [5,3,6,0],
    [2,6,1,0],
    [7,6,2,0],
    [3,1,4,0]
]

Z =  cvx.Minimize(cvx.sum(cvx.multiply(c,x)))
#Restricciones

print(cvx.multiply(c,x))

r=[
    #Oferta
    cvx.sum(x[0,:])<=50,
    cvx.sum(x[1,:])<=60,
    cvx.sum(x[2,:])<=50,
    cvx.sum(x[3,:])<=40,

    #Demanda

    cvx.sum(x[:,0])>=30,
    cvx.sum(x[:,1])>=70,
    cvx.sum(x[:,2])>=90,
    cvx.sum(x[:,3])>=10,
    
]

P = cvx.Problem(Z,r)
P.solve()
print(P.status)
print(round(P.value,2))
print(np.round(x.value,0))

[[5. 2. 7. 3.]
 [3. 6. 6. 1.]
 [6. 1. 2. 4.]
 [0. 0. 0. 0.]] @ var15383
optimal
400.0
[[ 0. 50.  0.  0.]
 [30.  0. 20. 10.]
 [ 0. 20. 30.  0.]
 [ 0.  0. 40.  0.]]


<h1>Maxi Cervezas</h1>
<img src="Maxi-Cervezas3.png">

In [100]:
## Caso demanda = oferta

# Caso oferta==Demanda

#Variable de decision
x=cvx.Variable((4,4),nonneg = True)

#Funcion objetivo

c = [
    [3,1,6,5],
    [7,5,1,1],
    [1,8,2,6],
    [6,9,4,2]
]

Z =  cvx.Minimize(cvx.sum(cvx.multiply(c,x)))
#Restricciones

print(cvx.multiply(c,x))

r=[
    #Oferta
    cvx.sum(x[0,:])<=80,
    cvx.sum(x[1,:])<=30,
    cvx.sum(x[2,:])<=60,
    cvx.sum(x[3,:])<=45,

    #Demanda

    cvx.sum(x[:,0])>=70,
    cvx.sum(x[:,1])>=40,
    cvx.sum(x[:,2])>=70,
    cvx.sum(x[:,3])>=35,
    
]

P = cvx.Problem(Z,r)
P.solve()
print(P.status)
print(round(P.value,2))
print(np.round(x.value,0))

[[3. 7. 1. 6.]
 [1. 5. 8. 9.]
 [6. 1. 2. 4.]
 [5. 1. 6. 2.]] @ var14272
optimal
360.0
[[40.  0. 40.  0.]
 [30.  0.  0.  0.]
 [ 0. 30. 30.  0.]
 [ 0. 10.  0. 35.]]


In [95]:
## Caso condicional

# Caso oferta==Demanda

#Variable de decision
x=cvx.Variable((4,4),nonneg = True)

#Funcion objetivo

c = [
    [5,3,6,4],
    [2,6,1,3],
    [7,6,2,6],
    [3,1,4,6]
]

Z =  cvx.Minimize(cvx.sum(cvx.multiply(c,x)))
#Restricciones

print(cvx.multiply(c,x))

r=[
    #Oferta
    cvx.sum(x[0,:])<=80,
    cvx.sum(x[1,:])<=30,
    cvx.sum(x[2,:])<=60,
    cvx.sum(x[3,:])<=45,

    #Demanda

    cvx.sum(x[:,0])>=70,
    cvx.sum(x[:,1])>=40,
    cvx.sum(x[:,2])>=70,
    cvx.sum(x[:,3])>=35,

    x[0,1]<=25
    
]

P = cvx.Problem(Z,r)
P.solve()
print(P.status)
print(round(P.value,2))
print(np.round(x.value,0))

[[5. 2. 7. 3.]
 [3. 6. 6. 1.]
 [6. 1. 2. 4.]
 [4. 3. 6. 6.]] @ var13310
optimal
650.0
[[27. 25.  6. 22.]
 [17.  0.  0. 13.]
 [ 0.  0. 60.  0.]
 [26. 15.  4.  0.]]


<h1>Problema de autos</h1>
<img src="Autos.png">

In [111]:
## Caso demanda = oferta

# Caso oferta==Demanda

#Variable de decision
x=cvx.Variable((3,2),nonneg = True)

#Funcion objetivo
a=82
b=50
c = [
    [1*a,1*100,1*102],
    [1*215,1*108,1*b]
]

Z =  cvx.Minimize(cvx.sum(cvx.multiply(c,x)))
#Restricciones

a=cvx.multiply(c,x)
print(a[0,0])
r=[
    #Oferta
    cvx.sum(x[0,:])<=1000,
    cvx.sum(x[1,:])<=1500,
    cvx.sum(x[2,:])<=1200,

    #Demanda

    cvx.sum(x[:,0])>=2300,
    cvx.sum(x[:,1])>=1400,
    
]

P = cvx.Problem(Z,r)
P.solve()
print(P.status)
print(round(P.value,2))
print(np.round(x.value,0))

[[ 82. 215.]
 [100. 108.]
 [102.  50.]] @ var16046[0, 0]
optimal
293600.0
[[1000.    0.]
 [1300.  200.]
 [   0. 1200.]]


In [78]:
import numpy as np

# Crear una matriz de 3x3 con valores aleatorios entre 0 y 1
matriz = np.random.rand(3, 3)

print(matriz[0,1])

print(matriz)

0.05113704752111581
[[0.58777905 0.05113705 0.81385394]
 [0.99808581 0.18839183 0.21898992]
 [0.377077   0.07828791 0.70191067]]
