<a href="https://colab.research.google.com/github/monicasofiarestrepo/InvestigacionDeOperaciones/blob/main/RutaCr%C3%ADtica_y_FlujoM%C3%A1ximoEntrenamiento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#@title Importar librerías
import cvxpy as cvx
import numpy as np

In [ ]:
# Variables de decisión
 #Ruta critica ej en clase
x = cvx.Variable((13,13), boolean = True)

# Función objetivo:
c = [
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [2,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,4,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,10,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,4,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,6,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,7,5,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,0,7,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,8,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,9,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,4,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,5,-99999,0,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,2,-99999,6,-99999],
  ]

Z = cvx.Maximize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # de oferta
     cvx.sum(x[0,:]) <= 1,

    # de demanda
     cvx.sum(x[:,12]) >= 1,

    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    cvx.sum(x[:,7]) - cvx.sum(x[7,:]) >= 0,
    cvx.sum(x[:,8]) - cvx.sum(x[8,:]) >= 0,
    cvx.sum(x[:,9]) - cvx.sum(x[9,:]) >= 0,
    cvx.sum(x[:,10]) - cvx.sum(x[10,:]) >= 0,
    cvx.sum(x[:,11]) - cvx.sum(x[11,:]) >= 0,
]

P = cvx.Problem(Z,r)
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))


optimal
44.0
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Flujo máximo

In [ ]:
# Variables de decisión
x = cvx.Variable((7,7), nonneg=True)

# Función objetivo
Z = cvx.Maximize(cvx.sum(x[:,6]))

# Restricciones

# capacidades de los enlaces
b = [
    [0,0,0,0,0,0,0],
    [5000,0,2000,0,0,0,0],
    [6000,2000,0,0,0,0,0],
    [5000,0,3000,0,0,0,0],
    [0,3000,3000,0,0,1000,0],
    [0,0,7000,5000,1000,0,0],
    [0,0,0,0,8000,7000,0],
]

r =[
    # de capacidad
    x <= b,

    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,

    # evitar carros atrapados en la ciudad
    cvx.sum(x[0,:]) == cvx.sum(x[:,6])
]

P = cvx.Problem(Z,r)
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
13999.999999789194
[[   0. 4331. 5520. 4149.    0.    0.    0.]
 [   0.    0. 1666.    0. 3000.    0.    0.]
 [   0.  334.    0.  325. 3000. 3526.    0.]
 [   0.    0.    0.    0.    0. 4474.    0.]
 [   0.    0.    0.    0.    0.    0. 7000.]
 [   0.    0.    0.    0. 1000.    0. 7000.]
 [   0.    0.    0.    0.    0.    0.    0.]]


In [ ]:
cvx.sum(x[0,:]).value
#todo lo que entra

13999.999999811067

#ENTRENAMIENTO

In [2]:
#@title Giga Wats / hora
# Variables de decisión
x = cvx.Variable((7,7), nonneg=True)

# Función objetivo
Z = cvx.Maximize(cvx.sum(x[:,6]))

# Restricciones

# capacidades de los enlaces
b = [
    [0   ,0   ,0   ,0   ,0   ,0   ,0   ],
    [25  ,0   ,8   ,0   ,0   ,0   ,0   ],
    [19  ,4   ,0   ,0   ,0   ,0   ,0   ],
    [9   ,0   ,2   ,0   ,0   ,0   ,0   ],
    [0   ,11  ,11  ,0   ,0   ,3   ,0   ],
    [0   ,0   ,9   ,4   ,10  ,0   ,0   ],
    [0   ,0   ,0   ,0   ,8   ,5   ,0   ],
]

r =[
    # de capacidad
    x <= b,

    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    

    # evitar perdida de energía
    cvx.sum(x[0,:]) == cvx.sum(x[:,6])
]

P = cvx.Problem(Z,r)
P.solve()

print(P.status)
print(round(P.value, 0))
print(np.round(x.value,0))

optimal
13.0
[[0. 5. 7. 1. 0. 0. 0.]
 [0. 0. 3. 0. 5. 0. 0.]
 [0. 3. 0. 1. 4. 2. 0.]
 [0. 0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 3. 8.]
 [0. 0. 0. 0. 2. 0. 5.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [4]:
#maximo flujo red 7x7 (de 0 a 6) 

# Variables de decisión
x = cvx.Variable((7,7), nonneg=True)

# Función objetivo
Z = cvx.Maximize(cvx.sum(x[:,6]))

# Restricciones

# capacidades de los enlaces
b = [
    [0 ,0 ,0 ,0 ,0 ,0 ,0 ],
    [10,0 ,1 ,0 ,0 ,0 ,0 ],
    [10,1 ,0 ,0 ,0 ,0 ,0 ],
    [0 ,8 ,0 ,0 ,3 ,0 ,0 ],
    [0 ,6 ,4 ,3 ,0 ,2 ,0 ],
    [0 ,0 ,12,0 ,2 ,0 ,0 ] ,
    [0 ,0 ,0 ,7 ,2 ,1 ,0 ],
]

r =[
    # de capacidad
    x <= b,

    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,

    # evitar atascados
    cvx.sum(x[0,:]) == cvx.sum(x[:,6])
]

P = cvx.Problem(Z,r)
P.solve()

print(P.status)
print(np.round(P.value,0))
print(np.round(x.value,0))

optimal
10.0
[[0. 6. 4. 0. 0. 0. 0.]
 [0. 0. 0. 5. 1. 0. 0.]
 [0. 1. 0. 0. 2. 2. 0.]
 [0. 0. 0. 0. 1. 0. 7.]
 [0. 0. 0. 2. 0. 1. 2.]
 [0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [5]:
#@title Flujo de Agua 
# Variables de decisión
x = cvx.Variable((7,7), nonneg=True)

# Función objetivo
Z = cvx.Maximize(cvx.sum(x[:,6]))

# Restricciones

# capacidades de los enlaces
b = [
    [0   ,0   ,0   ,0   ,0   ,0   ,0   ],
    [6   ,0   ,0   ,0   ,0   ,0   ,0   ],
    [4   ,0   ,0   ,0   ,0   ,0   ,0   ],
    [1   ,0   ,3   ,0   ,0   ,0   ,0   ],
    [0   ,4   ,1   ,0   ,0   ,0   ,0   ],
    [0   ,0   ,3   ,4   ,2   ,0   ,0   ],
    [0   ,0   ,0   ,0   ,4   ,9   ,0   ],
]

r =[
    # de capacidad
    x <= b,

    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,

    # evitar cagua estancada
    cvx.sum(x[0,:]) == cvx.sum(x[:,6])
]

P = cvx.Problem(Z,r)
P.solve()

print(P.status)
print(round(P.value, 0))
print(np.round(x.value,0))

optimal
9.0
[[0. 4. 4. 1. 0. 0. 0.]
 [0. 0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 2. 0. 2. 0.]
 [0. 0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 1. 3.]
 [0. 0. 0. 0. 0. 0. 6.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [3]:
#estudio de ingenieria de transito

#maximo flujo red 6x6

# Variables de decisión
x = cvx.Variable((8,8), nonneg=True)

# Función objetivo
Z = cvx.Maximize(cvx.sum(x[:,7]))

# Restricciones

# capacidades de los enlaces
b = [
    [0 ,0 ,0 ,0 ,0 ,0 ,0 ,0],
    [9 ,0 ,0 ,0 ,0 ,0 ,0 ,0],
    [25,0 ,0 ,0 ,0 ,0 ,0 ,0],
    [10,0 ,0 ,0 ,0 ,0 ,0 ,0],
    [0 ,10,20,0 ,0 ,0 ,0 ,0],
    [0 ,0 ,9 ,4 ,0 ,0 ,0 ,0] ,
    [0 ,0 ,0 ,15,0 ,0 ,0 ,0],
    [0 ,0 ,0 ,0 ,22,40,9 ,0],
]

r =[
    # de capacidad
    x <= b,

    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    cvx.sum(x[:,7]) - cvx.sum(x[7,:]) >= 0,

    # evitar atascados
    cvx.sum(x[0,:]) == cvx.sum(x[:,7])
]

P = cvx.Problem(Z,r)
P.solve()

print(P.status)
print(np.round(P.value,0))
print(np.round(x.value,0))

optimal
41.0
[[ 0.  8. 23. 10.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  8.  0.  0.  0.]
 [ 0.  0.  0.  0. 14.  9.  0.  0.]
 [ 0.  0.  0.  0.  0.  3.  7.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 22.]
 [ 0.  0.  0.  0.  0.  0.  0. 12.]
 [ 0.  0.  0.  0.  0.  0.  0.  7.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [ ]:
#@title Maximo flujo red 11x11

# Variables de decisión
x = cvx.Variable((11,11), nonneg=True)

# Función objetivo
Z = cvx.Maximize(cvx.sum(x[:,10]))

# Restricciones

# capacidades de los enlaces
b = [
    [0 ,0 ,0 ,0 ,0 ,0 ,0, 0, 0, 0, 0 ],
    [4 ,0 ,0 ,0 ,0 ,0 ,0, 0, 0, 0, 0 ],
    [6 ,5 ,0 ,4 ,0 ,0 ,0, 0, 0, 0, 0 ],
    [3 ,0 ,0 ,0 ,0 ,0 ,0, 0, 0, 0, 0 ],
    [0 ,3 ,2 ,0 ,0 ,0 ,0, 0, 0, 0, 0 ],
    [0 ,0 ,2 ,0 ,2 ,0 ,2, 0, 0, 0, 0 ],
    [0 ,0 ,5 ,6 ,0 ,0 ,0, 0, 0, 0, 0 ],
    [0 ,0 ,0 ,0 ,4 ,2 ,0, 0, 2, 0, 0 ],
    [0 ,0 ,0 ,0 ,0 ,5 ,2, 0, 0, 0, 0 ],
    [0 ,0 ,0 ,0 ,0 ,0 ,5, 0, 3, 0, 0 ],
    [0 ,0 ,0 ,0 ,0 ,0 ,0, 7, 8, 4, 0 ],

]

r =[
    # de capacidad
    x <= b,

    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    cvx.sum(x[:,7]) - cvx.sum(x[7,:]) >= 0,
    cvx.sum(x[:,8]) - cvx.sum(x[8,:]) >= 0,
    cvx.sum(x[:,9]) - cvx.sum(x[9,:]) >= 0,

    # evitar atascados
    cvx.sum(x[0,:]) == cvx.sum(x[:,10])
]

P = cvx.Problem(Z,r)
P.solve()

print(P.status)
print(np.round(P.value,0))
print(np.round(x.value,0))