<a href="https://colab.research.google.com/github/monicasofiarestrepo/InvestigacionDeOperaciones/blob/main/IO1_8_Transporte_clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cvxpy as cvx
import numpy as np

In [ ]:
# Variables de decisión
x = cvx.Variable((3,4), nonneg = True)

# Función objetivo:

c = [
    [464,352,995],
    [513,416,682],
    [654,690,388],
    [867,791,685]
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones

r = [
    # oferta
    cvx.sum(x[0,:]) <= 75,
    cvx.sum(x[1,:]) <= 125,
    cvx.sum(x[2,:]) <= 100,
     
     # demanda
    cvx.sum(x[:,0]) >= 80,
    cvx.sum(x[:,1]) >= 65,
    cvx.sum(x[:,2]) >= 70,
    cvx.sum(x[:,3]) >= 85,
          
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
152535.00004022144
[[ 0. 20.  0. 55.]
 [80. 45.  0.  0.]
 [ 0.  0. 70. 30.]]


In [ ]:
# Verificación del equilibrio: O == D
Toda la oferta del sistema : 300 (75+125+100)
Toda la demanda del sistema : 300 (80+65+70+85)



In [ ]:
# Caso 2: Desequilibrio O > D

# Variables de decisión
x = cvx.Variable((3,4), nonneg = True)

# Función objetivo:

c = [
    [464,352,995],
    [513,416,682],
    [654,690,388],
    [867,791,685]
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones

r = [
    # oferta
    cvx.sum(x[0,:]) <= 175,
    cvx.sum(x[1,:]) <= 125,
    cvx.sum(x[2,:]) <= 100,
     
     # demanda
    cvx.sum(x[:,0]) >= 80,
    cvx.sum(x[:,1]) >= 65,
    cvx.sum(x[:,2]) >= 70,
    cvx.sum(x[:,3]) >= 85,
          
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
152535.00002617802
[[ 0. 20.  0. 55.]
 [80. 45.  0.  0.]
 [ 0.  0. 70. 30.]]


In [ ]:
# Caso 2: Desequilibrio O > D y hay que repartir toda la oferta

# Variables de decisión
x = cvx.Variable((3,4), nonneg = True)

# Función objetivo:

c = [
    [464,352,995],
    [513,416,682],
    [654,690,388],
    [867,791,685]
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones

r = [
    # oferta
    cvx.sum(x[0,:]) <= 175,
    cvx.sum(x[1,:]) <= 125,
    cvx.sum(x[2,:]) <= 100,
     
     # demanda
    cvx.sum(x[:,0]) >= 80,
    cvx.sum(x[:,1]) >= 65,
    cvx.sum(x[:,2]) >= 70,
    cvx.sum(x[:,3]) >= 85,
     
    # repartir todo lo de Buriticá
    cvx.sum(x[0,:]) >= 175,
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
163060.00011393637
[[55. 65.  0. 55.]
 [25.  0.  0.  0.]
 [ 0.  0. 70. 30.]]


In [ ]:
# Desequilibrio O < D

# Variables de decisión
x = cvx.Variable((4,4), nonneg = True)

# Función objetivo:

c = [
    [464,352,995,0],
    [513,416,682,0],
    [654,690,388,0],
    [867,791,685,0]
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones

r = [
    # oferta
    cvx.sum(x[0,:]) <= 55,
    cvx.sum(x[1,:]) <= 125,
    cvx.sum(x[2,:]) <= 100,
    cvx.sum(x[3,:]) <= 20,
     
     # demanda
    cvx.sum(x[:,0]) >= 80,
    cvx.sum(x[:,1]) >= 65,
    cvx.sum(x[:,2]) >= 70,
    cvx.sum(x[:,3]) >= 85,
          
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
135195.00003374982
[[ 0. 20.  0. 35.]
 [80. 45.  0.  0.]
 [ 0.  0. 70. 30.]
 [ 0.  0.  0. 20.]]


In [ ]:
# Variables de decisión
x = cvx.Variable((3,4), nonneg = True)

# Función objetivo:

c = [
    [464,352,995],
    [513,416,682],
    [654,690,388],
    [867,791,685]
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones

r = [
    # oferta
    cvx.sum(x[0,:]) <= 75,
    cvx.sum(x[1,:]) <= 125,
    cvx.sum(x[2,:]) <= 100,
     
     # demanda
    cvx.sum(x[:,0]) >= 80,
    cvx.sum(x[:,1]) >= 65,
    cvx.sum(x[:,2]) >= 70,
    cvx.sum(x[:,3]) >= 85,
     
     # restricciones de los arcos
    x[0,3] >= 60,
          
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
154290.00000089023
[[ 0. 15.  0. 60.]
 [80. 45.  0.  0.]
 [ 0.  5. 70. 25.]]


In [ ]:
# Variables de decisión
x = cvx.Variable((3,4), nonneg = True)

# Función objetivo:

c = [
    [464,352,995],
    [513,416,682],
    [654,690,388],
    [999999,791,685]
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones

r = [
    # oferta
    cvx.sum(x[0,:]) <= 75,
    cvx.sum(x[1,:]) <= 125,
    cvx.sum(x[2,:]) <= 100,
     
     # demanda
    cvx.sum(x[:,0]) >= 80,
    cvx.sum(x[:,1]) >= 65,
    cvx.sum(x[:,2]) >= 70,
    cvx.sum(x[:,3]) >= 85,
     
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
153840.0002895294
[[10. 65.  0.  0.]
 [70.  0.  0. 55.]
 [ 0.  0. 70. 30.]]


In [ ]:
# Variables de decisión
x = cvx.Variable((3,4), nonneg = True)

# Función objetivo:

c = [
    [464,352,995],
    [513,416,682],
    [654,690,388],
    [867,791,685]
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones

r = [
    # oferta
    cvx.sum(x[0,:]) <= 175,
    cvx.sum(x[1,:]) <= 125,
    cvx.sum(x[2,:]) <= 100,
     
     # demanda
    cvx.sum(x[:,0]) >= 80,
    cvx.sum(x[:,1]) >= 65,
    cvx.sum(x[:,2]) >= 70,
    cvx.sum(x[:,3]) >= 85,
    
    cvx.sum(x[0,:]) >= 175,
    #cvx.sum(x) >= 175 + 125 + 100
         
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
198260.00001934275
[[ 55.  65.   0.  55.]
 [125.   0.   0.   0.]
 [  0.   0.  70.  30.]]
