<a href="https://colab.research.google.com/github/monicasofiarestrepo/InvestigacionDeOperaciones/blob/main/RutaCr%C3%ADtica_y_FlujoM%C3%A1ximo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#@title Importar librerías
import cvxpy as cvx
import numpy as np

In [ ]:
# Variables de decisión
x = cvx.Variable((13,13), boolean = True)

# Función objetivo:
c = [
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [2,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,4,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,10,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,4,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,6,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,7,5,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,0,7,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,8,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,9,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,4,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,5,-99999,0,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,2,-99999,6,-99999],
  ]

Z = cvx.Maximize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # de oferta
     cvx.sum(x[0,:]) <= 1,

    # de demanda
     cvx.sum(x[:,12]) >= 1,

    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    cvx.sum(x[:,7]) - cvx.sum(x[7,:]) >= 0,
    cvx.sum(x[:,8]) - cvx.sum(x[8,:]) >= 0,
    cvx.sum(x[:,9]) - cvx.sum(x[9,:]) >= 0,
    cvx.sum(x[:,10]) - cvx.sum(x[10,:]) >= 0,
    cvx.sum(x[:,11]) - cvx.sum(x[11,:]) >= 0,
]

P = cvx.Problem(Z,r)
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))


optimal
44.0
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Flujo máximo

In [ ]:
# Variables de decisión
x = cvx.Variable((7,7), nonneg=True)

# Función objetivo
Z = cvx.Maximize(cvx.sum(x[:,6]))

# Restricciones

# capacidades de los enlaces
b = [
    [0,0,0,0,0,0,0],
    [5000,0,2000,0,0,0,0],
    [6000,2000,0,0,0,0,0],
    [5000,0,3000,0,0,0,0],
    [0,3000,3000,0,0,1000,0],
    [0,0,7000,5000,1000,0,0],
    [0,0,0,0,8000,7000,0],
]

r =[
    # de capacidad
    x <= b,

    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,

    # evitar carros atrapados en la ciudad
    cvx.sum(x[0,:]) == cvx.sum(x[:,6])
]

P = cvx.Problem(Z,r)
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
13999.999999789194
[[   0. 4331. 5520. 4149.    0.    0.    0.]
 [   0.    0. 1666.    0. 3000.    0.    0.]
 [   0.  334.    0.  325. 3000. 3526.    0.]
 [   0.    0.    0.    0.    0. 4474.    0.]
 [   0.    0.    0.    0.    0.    0. 7000.]
 [   0.    0.    0.    0. 1000.    0. 7000.]
 [   0.    0.    0.    0.    0.    0.    0.]]


In [ ]:
cvx.sum(x[0,:]).value

13999.999999811067