<a href="https://colab.research.google.com/github/monicasofiarestrepo/InvestigacionDeOperaciones/blob/main/RutaCritica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cvxpy as cvx
import numpy as np

# Maqueta compañía constructora

| De/Hacia| 0 | 1  | 2 | 3 | 4 | 5 | 6 | 7 
| :-: | :-: | :-:  | :-: | :-: | :-: | :-: | :-: | :-: |
| 0 | -9999 | 30 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |
| 1 | -9999 | -9999 | 6 | 5 | 14 | -9999 | -9999 | -9999 |
| 2 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | c | -9999 |
| 3 | -9999 | -9999 | -9999 | -9999 | -9999 | 10 | -9999 | -9999 |
| 4 | -9999 | -9999 | 0 | -9999 | -9999 | 0 | -9999 | -9999 |
| 5 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | f | -9999 |
| 6 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | 2 |
| 7 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |


In [ ]:
# Variables de decisión
x = cvx.Variable((8,8), boolean = True)

# Función objetivo:
cc= 4
f= 8
c = [
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [30,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,6,-99999,-99999,0,-99999,-99999,-99999],
    [-99999,5,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,14,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,10,0,-99999,-99999,-99999],
    [-99999,-99999,cc,-99999,-99999,f,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,2,-99999],
  ]

Z = cvx.Maximize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # de oferta
     cvx.sum(x[0,:]) <= 1,

    # de demanda
     cvx.sum(x[:,7]) >= 1,

    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    
]

P = cvx.Problem(Z,r)
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))


optimal
55.0
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


RUTA CRÍTICA : 013567

# Construcción casa

| De/Hacia| 1 | 2 | 3  | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13
| :-: | :-: | :-:  | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| 1 | -9999 | a | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |
| 2 | -9999 |-9999|b| -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |
| 3 | -9999 |-9999|-9999| c | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |
| 4 | -9999 |-9999|-9999| -9999 | d | e | h | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |
| 5 | -9999 |-9999|-9999| -9999 | -9999 | -9999 | g | i | -9999 | -9999 | -9999 | -9999 | -9999 |
| 6 | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | f | -9999 | -9999 | -9999 | -9999 | -9999 |
| 7 | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | -9999 | n | -9999 | -9999 | -9999 | -9999 |
| 8 | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | k | -9999 | -9999 | -9999 |
| 9 | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | p | q | -9999 |
| 10 | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |  -9999 | -9999 | m |
| 11 | -9999 |-9999|-9999 |-9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | s | -9999 |
| 12 | -9999 |-9999|-9999 |-9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | v |
| 13 | -9999 |-9999|-9999 |-9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |

In [ ]:
# Variables de decisión
x = cvx.Variable((13,13), boolean = True)

# Función objetivo:
a = 8
b = 5
cc = 5
d = 2
e = 3
f = 7
g = 7
h = 2
i = 9
k = 2
m = 8
n = 7
p = 5
q = 4
s = 6
v = 2

c = [
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [a,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,b,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,cc,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,d,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,e,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,h,g,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,i,f,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,n,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,k,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,p,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,q,-99999,s,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,m,-99999,v,-99999],
  ]

Z = cvx.Maximize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # de oferta
     cvx.sum(x[0,:]) <= 1,

    # de demanda
     cvx.sum(x[:,12]) >= 1,

    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    cvx.sum(x[:,7]) - cvx.sum(x[7,:]) >= 0,
    cvx.sum(x[:,8]) - cvx.sum(x[8,:]) >= 0,
    cvx.sum(x[:,9]) - cvx.sum(x[9,:]) >= 0,
    cvx.sum(x[:,10]) - cvx.sum(x[10,:]) >= 0,
    cvx.sum(x[:,11]) - cvx.sum(x[11,:]) >= 0,
]

P = cvx.Problem(Z,r)
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))



optimal
47.0
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


RUTA CRÍTICA : 1234579111213

# Maquina (Solo da en unos casos)



| De/Hacia| A | B  | C | D | E | F | G | T |
| :-: | :-: | :-:  | :-: | :-: | :-: | :-: | :-: | :-: |
| A | -9999 | -9999 | -9999 | 4 | 4 | -9999 | -9999 | -9999 |
| B | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | a | -9999 |
| C | -9999 | -9999 | -9999 | -9999 | -9999 | 3 | -9999 | -9999 |
| D | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | 3 | -9999 |
| E | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | 6 |
| F | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | 5 |
| G | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | b |
| T | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |

In [ ]:
# Variables de decisión
x = cvx.Variable((8,8), boolean = True)

# Función objetivo:
a=2
b=3
c = [
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [4,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [4,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,3,-99999,-99999,-99999,-99999,-99999],
    [-99999,a,-99999,3,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,6,5,b,-99999],
]

Z = cvx.Maximize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # de oferta
     cvx.sum(x[0,:]) <= 1, 

    # de demanda
     cvx.sum(x[:,7]) >= 1,

    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    
]

P = cvx.Problem(Z,r)
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
10.0
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


# Seminario

| De/Hacia| A | B | C  | D | E | F | G | H | I | J | K | L | M | N | T
| :-: | :-: | :-:  | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| A | -9999 | 25 | 25 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |
| B | -9999 |-9999|-9999| 5 | -9999 | 5 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |
| C | -9999 |-9999|-9999| -9999 | 10 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |
| D | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | 10 | -9999 | -9999 | -9999 | -9999 |
| E | -9999 |-9999|-9999| -9999 | -9999 | -9999 | a | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |
| F | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | -9999 | 12 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |
| G | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | 15 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |
| H | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | 15| -9999 | -9999 | -9999 | -9999 | -9999 |
| I | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | 12 | -9999 | -9999 | -9999 | -9999 | -9999 |
| J | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | 20 | -9999 | -9999 | -9999 | -9999 |
| K | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | 10 | -9999 | -9999 | -9999 |
| L | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | b | -9999 | -9999 |
| M | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | 25 | -9999 |
| N | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | 10 |
| T | -9999 |-9999|-9999| -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 | -9999 |

In [ ]:
# Variables de decisión
x = cvx.Variable((15,15), boolean = True)

# Función objetivo:
a=13
b=2
c = [
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [25,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [25,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,5,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-9999,10,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,5,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,a,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,15,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,12,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,15,12,-99999,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,10,-99999,-99999,-99999,-99999,-99999,20,-99999,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,10,-99999,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,b,-99999,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,25,-99999,-99999],
    [-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,-99999,10,-99999],
]

Z = cvx.Maximize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # de oferta
     cvx.sum(x[0,:]) <= 1,

    # de demanda
     cvx.sum(x[:,14]) >= 1,

    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    cvx.sum(x[:,7]) - cvx.sum(x[7,:]) >= 0,
    cvx.sum(x[:,8]) - cvx.sum(x[8,:]) >= 0,
    cvx.sum(x[:,9]) - cvx.sum(x[9,:]) >= 0,
    cvx.sum(x[:,10]) - cvx.sum(x[10,:]) >= 0,
    cvx.sum(x[:,11]) - cvx.sum(x[11,:]) >= 0,
    cvx.sum(x[:,12]) - cvx.sum(x[12,:]) >= 0,
    cvx.sum(x[:,13]) - cvx.sum(x[13,:]) >= 0,
     
    
]

P = cvx.Problem(Z,r)
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
145.0
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
