<a href="https://colab.research.google.com/github/monicasofiarestrepo/InvestigacionDeOperaciones/blob/main/Transporte8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cvxpy as cvx
import numpy as np

#Minas


O=D

In [ ]:
# Variables de decisión
x = cvx.Variable((3,4), nonneg = True)

# Función objetivo:

c = [
    [751,419,307],
    [392,896,335],
    [987,385,400],
    [663,542,317]
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones

r = [
    # oferta
    cvx.sum(x[0,:]) <= 75,
    cvx.sum(x[1,:]) <= 125,
    cvx.sum(x[2,:]) <= 100,

     # demanda
    cvx.sum(x[:,0]) >= 80,
    cvx.sum(x[:,1]) >= 65,
    cvx.sum(x[:,2]) >= 70,
    cvx.sum(x[:,3]) >= 85,

]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
113555.00000850465
[[ 0. 65.  0. 10.]
 [55.  0. 70.  0.]
 [25.  0.  0. 75.]]


O=D Variación


In [ ]:
# Variables de decisión
x = cvx.Variable((3,4), nonneg = True)

# Función objetivo:

c = [
    [967,529,312],
    [836,783,773],
    [931,446,749],
    [874,493,792]
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones

r = [
    # oferta
    cvx.sum(x[0,:]) <= 75,
    cvx.sum(x[1,:]) <= 125,
    cvx.sum(x[2,:]) <= 100,

     # demanda
    cvx.sum(x[:,0]) >= 80,
    cvx.sum(x[:,1]) >= 65,
    cvx.sum(x[:,2]) >= 70,
    cvx.sum(x[:,3]) >= 85,

]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
162215.0000131683
[[ 0. 65.  0. 10.]
 [ 0.  0. 70. 55.]
 [80.  0.  0. 20.]]


#Turbinas

In [ ]:
# variables de decisión
x = cvx.Variable((4,1), nonneg = True)
c_x = [[190,239,179,253]]
#[238,384,132,430]
#[354,183,138,385]

cm = 2
a = cvx.Variable((4,1), nonneg = True)
c_a = [[cm,cm,cm,cm]]

# Definir la función objetivo
Z = cvx.Minimize(cvx.sum(cvx.multiply(c_x,x)) + cvx.sum(cvx.multiply(c_a,a)))

# Restricciones
r = [
     # Restricciones de oferta
     x[0] <= 21,
     x[1] <= 33,
     x[2] <= 28,
     x[3] <= 21,

     # restricciones de demanda
     x[0] - a[0] >= 10,
     x[1] + a[0] - a[1] >= 15,
     x[2] + a[1] - a[2] >= 25,
     x[3] + a[2] - a[3] >= 20
    ]

# Configuración del problema
P = cvx.Problem(Z,r)

# Resolver
P.solve()

# Resultados
print(P.status)
print(np.round(P.value,1))
print(np.round(x.value,0))

optimal
14117.0
[[21.]
 [21.]
 [28.]
 [ 0.]]


#Aguas

O>D

In [ ]:
# Variables de decisión
x = cvx.Variable((3,4), nonneg = True)

# Función objetivo:

c = [
    [5,3,6],
    [2,6,1],
    [7,6,2],
    [3,1,4]
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones

r = [
    # oferta
    cvx.sum(x[0,:]) <= 50,
    cvx.sum(x[1,:]) <= 60,
    cvx.sum(x[2,:]) <= 50,

     # demanda
    cvx.sum(x[:,0]) >= 30,
    cvx.sum(x[:,1]) >= 70,
    cvx.sum(x[:,2]) >= 0,
    cvx.sum(x[:,3]) >= 10,

]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
190.00000009265557
[[ 0. 20.  0.  0.]
 [30.  0.  0. 10.]
 [ 0. 50.  0.  0.]]


 O<D

In [ ]:
# Variables de decisión
x = cvx.Variable((4,4), nonneg = True)

# Función objetivo:

c = [
    [8,3,6,0],
    [4,6,3,0],
    [4,6,2,0],
    [3,1,4,0]
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones

r = [
    # oferta
    cvx.sum(x[0,:]) <= 50,
    cvx.sum(x[1,:]) <= 60,
    cvx.sum(x[2,:]) <= 50,
    cvx.sum(x[3,:]) <= 40,

     # demanda
    cvx.sum(x[:,0]) >= 30,
    cvx.sum(x[:,1]) >= 70,
    cvx.sum(x[:,2]) >= 90,
    cvx.sum(x[:,3]) >= 10,

]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
519.9999999969762
[[ 0. 34. 16.  0.]
 [30. 11.  9. 10.]
 [ 0.  0. 50.  0.]
 [ 0. 26. 14.  0.]]


O>D y se debe repartir todo

In [ ]:
# Variables de decisión
x = cvx.Variable((3,4), nonneg = True)

# Función objetivo:

c = [
    [5,3,6],
    [5,6,1],
    [7,6,2],
    [1,1,4]
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones

r = [
    # oferta
    cvx.sum(x[0,:]) <= 50,
    cvx.sum(x[1,:]) <= 60,
    cvx.sum(x[2,:]) <= 50,

     # demanda
    cvx.sum(x[:,0]) >= 30,
    cvx.sum(x[:,1]) >= 70,
    cvx.sum(x[:,2]) >= 0,
    cvx.sum(x[:,3]) >= 10,

    cvx.sum(x[0,:]) >= 50,
    cvx.sum(x[1,:]) >= 60,
    cvx.sum(x[2,:]) >= 50,
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,5))

optimal
300.00000002239943
[[ 0. 20.  0. 30.]
 [30.  0.  0. 30.]
 [ 0. 50.  0.  0.]]


#Cervezas

O=D

In [ ]:
# Variables de decisión
x = cvx.Variable((4,4), nonneg = True)

# Función objetivo:

c = [
    [2,5,6,5],
    [5,5,1,1],
    [2,7,2,6],
    [3,1,4,2]
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones

r = [
    # oferta
    cvx.sum(x[0,:]) <= 80,
    cvx.sum(x[1,:]) <= 30,
    cvx.sum(x[2,:]) <= 60,
    cvx.sum(x[3,:]) <= 45,


     # demanda
    cvx.sum(x[:,0]) >= 70,
    cvx.sum(x[:,1]) >= 40,
    cvx.sum(x[:,2]) >= 70,
    cvx.sum(x[:,3]) >= 35,

]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
360.00000001624426
[[70.  0. 10.  0.]
 [ 0.  0.  0. 30.]
 [ 0.  0. 60.  0.]
 [ 0. 40.  0.  5.]]


Variación + restricción

In [ ]:
# Variables de decisión
x = cvx.Variable((4,4), nonneg = True)

# Función objetivo:

c = [
    [5,3,6,4],
    [2,6,1,3],
    [7,6,2,6],
    [3,1,4,6]
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones

r = [
    # oferta
    cvx.sum(x[0,:]) <= 80,
    cvx.sum(x[1,:]) <= 30,
    cvx.sum(x[2,:]) <= 60,
    cvx.sum(x[3,:]) <= 45,


     # demanda
    cvx.sum(x[:,0]) >= 70,
    cvx.sum(x[:,1]) >= 40,
    cvx.sum(x[:,2]) >= 70,
    cvx.sum(x[:,3]) >= 35,

    # restricciones de los arcos
    x[0,1] <= 25,
]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
650.000000015143
[[27. 25.  6. 22.]
 [17.  0.  0. 13.]
 [ 0.  0. 60.  0.]
 [26. 15.  4.  0.]]


#Autos

In [ ]:
# Variables de decisión
x = cvx.Variable((3,2), nonneg = True)

# Función objetivo:
a = 82
b = 50

c = [
    [a,100,102],
    [215,108,b]
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones

r = [
    # oferta
    cvx.sum(x[0,:]) <= 1000,
    cvx.sum(x[1,:]) <= 1500,
    cvx.sum(x[2,:]) <= 1200,

     # demanda
    cvx.sum(x[:,0]) >= 2300,
    cvx.sum(x[:,1]) >= 1400,

]

# Configurar el problema
P = cvx.Problem(Z,r)

# Solucionar
P.solve()

print(P.status)
print(P.value)
print(np.round(x.value,0))

optimal
293599.9999985016
[[1000.    0.]
 [1300.  200.]
 [   0. 1200.]]
