In [2]:
import cvxpy as cvx
import numpy as np

# Cuadrilla de mantenimiento

<img src="IO1.png">

Matriz:

| De/Hacia| 1 | 2  | 3 | 4 | 5 | 6 |
| :-: | :-: | :-:  | :-: | :-: | :-: | :-: |
| 1 | 9999 | 29 | 18 | 9999 | 9999 | 9999 |
| 2 | 9999 | 9999 | 2 | 3 | 9999 | 11 |
| 3 | 9999| 2 | 9999 | 9999 | 2 | 9999 |
| 4 | 9999 | 3 | 9999 | 9999 | 3 | 14 |
| 5 | 9999 | 9999 | 2 | 3 | 9999 | 7 | 
| 6 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |


In [4]:
# Variables de decisión
x = cvx.Variable((6,6),boolean=True)

# Función objetivo
c = [
    [99999,99999,99999,99999,99999,99999],
    [29,99999,2,3,99999,99999],
    [18,2,99999,99999,2,99999],
    [99999,3,99999,99999,3,99999],
    [99999,99999,2,3,99999,99999],
    [99999,11,99999,14,7,99999],
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # de oferta
    cvx.sum(x[0,:]) <= 1,

    # de demanda
    cvx.sum(x[:,5]) >= 1,

     
    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,

]

P = cvx.Problem(Z,r)
P.solve()

# impresiones
print(P.status)
print(np.round(P.value,0))
print(np.round(x.value,0))

optimal
27.0
[[ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0. -0.  0.]
 [ 0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.]]


# Derrumbe en la mina

<img src="IO2.png">

Matriz:

| De/Hacia| 0 | 1 | 2  | 3 | 4 | 5 | 6 | 7 | 8 |
| :-: | :-: | :-:  | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| 0 | 9999 | 4 | 2 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |
| 1 | 9999 | 9999 | 2 | 7 | 9999 | 9999 | 9999 | 9999 | 9999 |
| 2 | 9999 | 4 | 9999 | 9 | 6 | 9999 | 9999 | 9999 | 9999 |
| 3 | 9999 | 9999 | 9999 | 9999 | 9999 | 1 | 6 | 9999 | 9999 |
| 4 | 9999 | 9999 | 9999 | 2 | 9999 | 4 | 3 | 2 | 9999 |
| 5 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 1 | 9999 | 5 |
| 6 | 9999 | 9999 | 9999 | 9999 | 9999 | 4 | 9999 | 3 | 5 |
| 7 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 3 | 9999 | 7 | 
| 8 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |

In [5]:
# Variables de decisión
x = cvx.Variable((9,9),boolean=True)

# Función objetivo
c = [
    [9999,9999,9999,9999,9999,9999,9999,9999,9999],
    [9999, 4  ,9999, 4  ,9999,9999,9999,9999,9999],
    [ 2  , 2  ,9999,9999,9999,9999,9999,9999,9999],
    [9999, 7  , 9  ,9999, 2  ,9999,9999,9999,9999],
    [9999,9999, 6  ,9999,9999,9999,9999,9999,9999],
    [9999,9999,9999, 1  , 4  ,9999, 4  ,9999,9999],
    [9999,9999,9999, 6  , 3  , 1  ,9999, 3  ,9999],
    [9999,9999,9999,9999, 2  ,9999, 3  ,9999,9999],
    [9999,9999,9999,9999,9999, 5  , 5  , 7  ,9999],
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # de oferta
    cvx.sum(x[0,:]) <= 1,

    # de demanda
    cvx.sum(x[:,8]) >= 1,

     
    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    cvx.sum(x[:,7]) - cvx.sum(x[7,:]) >= 0,

]

P = cvx.Problem(Z,r)
P.solve()

# impresiones
print(P.status)
print(np.round(P.value,0))
print(np.round(x.value,0))

optimal
16.0
[[ 0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


# Luciana

<img src="IO3.png">

Matriz:

| De/Hacia| A | B  | C | D | E | F | G |
| :-: | :-: | :-:  | :-: | :-: | :-: | :-: | :-: |
| A | 9999 | 12 | 4 | 9999 | 9999 | 9999 | 9999 |
| B | 9999 | 9999 | 9999 | 5 | 3 | 9999 | 9999 |
| C | 9999| 9999 | 9999 | 2 | 9999 | 10 | 9999 |
| D | 9999 | 9999 | 9999 | 9999 | 10 | 9999 | 9999 |
| E | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |  2 |
| F | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 4 |
| G | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |

In [12]:
# Variables de decisión
x = cvx.Variable((7,7),boolean=True)

# Función objetivo
c = [
    [99999,99999,99999,99999,99999,99999,99999],
    [ 12  ,99999,99999,99999,99999,99999,99999],
    [  4  ,99999,99999,99999,99999,99999,99999],
    [99999,  5  ,  2  ,99999,99999,99999,99999],
    [99999,  3  ,99999, 10  ,99999,99999,99999],
    [99999,99999, 10  ,99999,99999,99999,99999],
    [99999,99999,99999,99999,  2  ,  4  ,99999],
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # de oferta
    cvx.sum(x[0,:]) <= 1,

    # de demanda
    cvx.sum(x[:,6]) >= 1,

     
    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,

]

P = cvx.Problem(Z,r)
P.solve()

# impresiones
print(P.status)
print(np.round(P.value,0))
print(np.round(x.value,0))

optimal
17.0
[[ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0. -0.  0.]
 [ 0.  0.  0.  0. -0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


# Red 11x11

<img src="IO4.png">

Matriz:

| De/Hacia| O | A | B  | C | D | E | F | G | H | I | T | 
| :-: | :-: | :-:  | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| O | 9999 | 4 | 3 | 6 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |
| A | 9999 |9999|9999| 5 | 3 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |
| B | 9999 |9999|9999| 4 | 9999 | 6 | 9999 | 9999 | 9999 | 9999 | 9999 |
| C | 9999 |9999|9999| 9999 | 2 | 5 | 2 | 9999 | 9999 | 9999 | 9999 |
| D | 9999 |9999|9999| 9999 | 9999 | 9999 | 2 | 4 | 9999 | 9999 | 9999 |
| E | 9999 |9999|9999| 9999 | 9999 | 9999 | 1 | 9999 | 2 | 5 | 9999 |
| F | 9999 |9999|9999| 9999 | 9999 | 9999 | 9999 | 2 | 5 | 9999 | 9999 |
| G | 9999 |9999|9999| 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 7 |
| H | 9999 |9999|9999| 9999 | 9999 | 9999 | 9999 | 2 | 9999 | 3 | 8 |
| I | 9999 |9999|9999| 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 4 |
| T | 9999 |9999|9999 |9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |

In [15]:
# Variables de decisión
x = cvx.Variable((11,11),boolean=True)

# Función objetivo
c = [
    [99999,99999,99999,99999,99999,99999,99999,99999,99999,99999,99999],
    [  4  ,99999,99999,99999,99999,99999,99999,99999,99999,99999,99999],
    [  3  ,99999,99999,99999,99999,99999,99999,99999,99999,99999,99999],
    [  6  ,  5  ,  4  ,99999,99999,99999,99999,99999,99999,99999,99999],
    [99999,  3  ,99999,  2  ,99999,99999,99999,99999,99999,99999,99999],
    [99999,99999,  6  ,  5  ,99999,99999,99999,99999,99999,99999,99999],
    [99999,99999,99999,  2  ,  2  ,  1  ,99999,99999,99999,99999,99999],
    [99999,99999,99999,99999,  4  ,99999,  2  ,99999,  2  ,99999,99999],
    [99999,99999,99999,99999,99999,  2  ,  5  ,99999,99999,99999,99999],
    [99999,99999,99999,99999,99999,  5  ,99999,99999,  3  ,99999,99999],
    [99999,99999,99999,99999,99999,99999,99999,  7  ,  8  ,  4  ,99999],

]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # de oferta
    cvx.sum(x[0,:]) <= 1,

    # de demanda
    cvx.sum(x[:,10]) >= 1,

     
    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    cvx.sum(x[:,7]) - cvx.sum(x[7,:]) >= 0,
    cvx.sum(x[:,8]) - cvx.sum(x[8,:]) >= 0,
    cvx.sum(x[:,9]) - cvx.sum(x[9,:]) >= 0,
     
]

P = cvx.Problem(Z,r)
P.solve()

# impresiones
print(P.status)
print(np.round(P.value,0))
print(np.round(x.value,0))

optimal
17.0
[[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#  Compañía de transporte

<img src="IO5.png">

Matriz:

| De/Hacia| A | B  | C | D | E | F | G | H | I | J |
| :-: | :-: | :-:  | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| A | 9999 |2|4| 4 | 9999 | 9999 | 9999 | 9999 | 9999 |  9999 |
| B | 9999 |9999|9999|9999| 7 | 4 | 6 | 9999 | 9999 | 9999 |
| C | 9999 |9999|9999| 9999 | 3 | 2 | 4 | 9999 | 9999 | 9999 |
| D | 9999 |9999|9999| 9999 | 4 | 1 | 5 | 9999 | 9999 | 9999 |
| E | 9999 |9999|9999| 9999 | 9999 | 9999 | 9999 | 1 | 4 | 9999 |
| F | 9999 |9999|9999| 9999 | 9999 | 9999 | 9999 | 6 | 3 | 9999 |
| G | 9999 |9999|9999| 9999 | 9999 | 9999 | 9999 | 3 | 3 | 9999 |
| H | 9999 |9999|9999| 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 3 |
| I | 9999 |9999|9999| 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 4 |
| J | 9999 |9999|9999| 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |


In [17]:
# Variables de decisión
x = cvx.Variable((10,10),boolean=True)

# Función objetivo
c = [
    [99999,99999,99999,99999,99999,99999,99999,99999,99999,99999],
    [  2  ,99999,99999,99999,99999,99999,99999,99999,99999,99999],
    [  4  ,99999,99999,99999,99999,99999,99999,99999,99999,99999],
    [  4  ,99999,99999,99999,99999,99999,99999,99999,99999,99999],
    [99999,  7  ,  3  ,  4  ,99999,99999,99999,99999,99999,99999],
    [99999,  4  ,  2  ,  1  ,99999,99999,99999,99999,99999,99999],
    [99999,  6  ,  4  ,  5  ,99999,99999,99999,99999,99999,99999],
    [99999,99999,99999,99999,  1  ,  6  ,  3  ,99999,99999,99999],
    [99999,99999,99999,99999,  4  ,  3  ,  3  ,99999,99999,99999],
    [99999,99999,99999,99999,99999,99999,99999,  3  ,  4  ,99999],
    
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # de oferta
    cvx.sum(x[0,:]) <= 1,

    # de demanda
    cvx.sum(x[:,9]) >= 1,
     
    # de transbordo
    cvx.sum(x[:,1]) - cvx.sum(x[1,:]) >= 0,
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 0,
    cvx.sum(x[:,6]) - cvx.sum(x[6,:]) >= 0,
    cvx.sum(x[:,7]) - cvx.sum(x[7,:]) >= 0,
    cvx.sum(x[:,8]) - cvx.sum(x[8,:]) >= 0,


]

P = cvx.Problem(Z,r)
P.solve()

# impresiones
print(P.status)
print(np.round(P.value,0))
print(np.round(x.value,0))

optimal
11.0
[[ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
