In [1]:
import cvxpy as cvx
import numpy as np

# Servidores de correo electrónico

<img src="IO1.png">

Matriz:

| De/Hacia| O1 | O2  | T1 | T2 | D1 | D2 | D3 |
| :-: | :-: | :-:  | :-: | :-: | :-: | :-: | :-: |
| O1 | 9999 | 9999 | 3 | 4 | 9999 | 9999 | 9999 |
| O2 | 9999 | 9999 | 2 | 5 | 9999 | 9999 | 9999 |
| T1 | 9999| 9999| 9999 | 7 | 8 | 6 | 9999 |
| T2 | 9999 | 9999|  9999 | 9999 | 9999 | 4 | 9 |
| D1 | 9999 | 9999 | 9999 | 9999 | 9999 | 5 | 9999 |
| D2 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 3 |
| D3 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |


In [16]:
# Variables de decisión
x = cvx.Variable((7,7), nonneg=True)

# Función objetivo
c = [
    [999999,999999,999999,999999,999999,999999,999999],
    [999999,999999,999999,999999,999999,999999,999999],
    [3,2,999999,999999,999999,999999,999999],
    [4,5,7,999999,999999,999999,999999],
    [999999,999999,8,999999,999999,999999,999999],
    [999999,999999,6,4,5,999999,999999],
    [999999,999999,999999,9,999999,3,999999],
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # de oferta O1 y O2
    cvx.sum(x[0,:]) <= 1000,
    cvx.sum(x[1,:]) <= 1200,
  
     
    # de demanda D3 
    cvx.sum(x[:,6]) >= 500,

   
    # de transbordo T1, T2, D1 y D2
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 800,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 900,    
  ]

P = cvx.Problem(Z,r)
P.solve()

# impresiones
print(P.status)
print(np.round(P.value,0))
print(np.round(x.value,0))

optimal
20700.0
[[   0.    0.    0. 1000.    0.    0.    0.]
 [   0.    0. 1200.    0.    0.    0.    0.]
 [   0.    0.    0.    0.  800.  400.    0.]
 [   0.    0.    0.    0.    0. 1000.    0.]
 [   0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.  500.]
 [   0.    0.    0.    0.    0.    0.    0.]]


# Barriles de fuel oil 

<img src="IO2.png">

| De/Hacia| Ref.1 | Ref.2  | cc.1 | cc.2 | Bari | Porto | Vita | Siena |
| :-: | :-: | :-:  | :-: | :-: | :-: | :-: | :-: | :-: |
| Ref.1 | 9999 | 9999 | 59 | 38 | 9999 | 9999 | 9999 | 9999 |
| Ref.2 | 9999 | 9999 | 17 | 10 | 9999 | 9999 | 9999 | 9999 |
| cc.1 | 9999| 9999| 9999 | 9999 | 15 | 68 | 70 | 70 |
| cc.2 | 9999 | 9999|  9999 | 9999 | 61 | 47 | 12 | 52 |
| Bari | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |
| Porto | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |
| Vita | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |
| Siena | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |

In [8]:
# Variables de decisión
x = cvx.Variable((8,8), nonneg=True)

# Función objetivo
c = [
    [999999,999999,999999,999999,999999,999999,999999,999999],
    [999999,999999,999999,999999,999999,999999,999999,999999],
    [59,17,999999,999999,999999,999999,999999,999999],
    [38,10,999999,999999,999999,999999,999999,999999],
    [999999,999999,15,61,999999,999999,999999,999999],
    [999999,999999,68,47,999999,999999,999999,999999],
    [999999,999999,70,12,999999,999999,999999,999999],
    [999999,999999,70,52,999999,999999,999999,999999],
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # de oferta
    cvx.sum(x[0,:]) <= 600,
    cvx.sum(x[1,:]) <= 400,
     
    # de demanda
    cvx.sum(x[:,4]) >= 200,
    cvx.sum(x[:,5]) >= 150,
    cvx.sum(x[:,6]) >= 350,
    cvx.sum(x[:,7]) >= 300, 
     
    # de transbordo
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
  
  ]

P = cvx.Problem(Z,r)
P.solve()

# impresiones
print(P.status)
print(np.round(P.value,0))
print(np.round(x.value,0))

optimal
58050.0
[[  0.   0.   0. 600.   0.   0.   0.   0.]
 [  0.   0. 200. 200.   0.   0.   0.   0.]
 [  0.   0.   0.   0. 200.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 150. 350. 300.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]]


# Galones de combustible

<img src="IO3.png">

| De/Hacia| 1 | 2  | 3 | 4 | 5 | 6 | 7 |
| :-: | :-: | :-:  | :-: | :-: | :-: | :-: | :-: |
| 1 | 9999 | 9999 | 3 | 9999 | 9999 | 9999 | 20 |
| 2 | 9999 | 9999 | 9 | 9999 | 9999 | 30 | 9999 |
| 3 | 9999 | 9999| 9999 | 9999 | 10 | 9999 | 40 |
| 4 | 9999 | 9999|  9999 | 9999 | 4 | 9999 | 8 |
| 5 | 9999 | 9999 | 10 | 4 | 9999 | 2 | 9999 |
| 6 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |
| 7 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |


In [12]:
# Variables de decisión
x = cvx.Variable((7,7), nonneg=True)

# Función objetivo
c = [
    [999999,999999,999999,999999,999999,999999,999999],
    [999999,999999,999999,999999,999999,999999,999999],
    [3,9,999999,999999,10,999999,999999],
    [999999,999999,999999,999999,4,999999,999999],
    [999999,999999,10,4,999999,999999,999999],
    [999999,30,999999,999999,2,999999,999999],
    [20,999999,40,8,999999,999999,999999],
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # de oferta
    cvx.sum(x[0,:]) <= 5000,
    cvx.sum(x[1,:]) <= 6000,
     
    # de demanda
    cvx.sum(x[:,5]) >= 2000,
    cvx.sum(x[:,6]) >= 9000,
     
    # de transbordo
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 0,
  ]

P = cvx.Problem(Z,r)
P.solve()

# impresiones
print(P.status)
print(np.round(P.value,0))
print(np.round(x.value,0))

optimal
266000.0
[[   0.    0.    0.    0.    0.    0. 5000.]
 [   0.    0. 6000.    0.    0.    0.    0.]
 [   0.    0.    0.    0. 6000.    0.    0.]
 [   0.    0.    0.    0.    0.    0. 4000.]
 [   0.    0.    0. 4000.    0. 2000.    0.]
 [   0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.]]


# Red de transporte Minas 

<img src="IO4.png">

| De/Hacia| M1 | M2  | cc1 | cc2 | D1 | D2 | D3 |
| :-: | :-: | :-:  | :-: | :-: | :-: | :-: | :-: |
| M1 | 9999 | 9999 | 14 | 9 | 9999 | 9999 | 9999 |
| M2 | 9999 | 9999 | 3 | 2 | 9999 | 9999 | 9999 |
| cc1 | 9999 | 9999 | 9999 | 0 | 3 | 14 | 9999 |
| cc2 | 9999 | 9999|  9999 | 9999 | 9999 | 11 | 2 |
| D1 | 9999 | 9999 | 9999 | 9999 | 9999 | 12 | 9999 |
| D2 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 13 |
| D3 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 | 9999 |

In [14]:
# Variables de decisión
x = cvx.Variable((7,7), nonneg=True)

# Función objetivo
c = [
    [999999,999999,999999,999999,999999,999999,999999],
    [999999,999999,999999,999999,999999,999999,999999],
    [14,3,999999,999999,999999,999999,999999],
    [9,2,0,999999,999999,999999,999999],
    [999999,999999,3,999999,999999,999999,999999],
    [999999,999999,14,11,12,999999,999999],
    [999999,999999,999999,2,999999,13,999999],
]

Z = cvx.Minimize(cvx.sum(cvx.multiply(c,x)))

# Restricciones
r = [
    # de oferta
    cvx.sum(x[0,:]) <= 1000,
    cvx.sum(x[1,:]) <= 1200,
     
    # de demanda
    cvx.sum(x[:,6]) >= 500,
     
    # de transbordo
    cvx.sum(x[:,2]) - cvx.sum(x[2,:]) >= 0,
    cvx.sum(x[:,3]) - cvx.sum(x[3,:]) >= 0,
    cvx.sum(x[:,4]) - cvx.sum(x[4,:]) >= 800,
    cvx.sum(x[:,5]) - cvx.sum(x[5,:]) >= 900,  
  ]

P = cvx.Problem(Z,r)
P.solve()

# impresiones
print(P.status)
print(np.round(P.value,0))
print(np.round(x.value,0))

optimal
25500.0
[[   0.    0.    0. 1000.    0.    0.    0.]
 [   0.    0.  800.  400.    0.    0.    0.]
 [   0.    0.    0.    0.  800.    0.    0.]
 [   0.    0.    0.    0.    0.  900.  500.]
 [   0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.]]
